apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: vigilantai
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: vigilantai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
