[package]
name = "backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tower-http.workspace = true
dotenvy.workspace = true
anyhow.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true
sqlx.workspace = true
redis.workspace = true
async-trait = "0.1"
tower = { version = "0.5", features = ["util"] }
argon2.workspace = true
jsonwebtoken.workspace = true
axum-extra.workspace = true
sha2 = "0.10"
image = "0.25"
bytes = "1"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
tempfile = "3"
