apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: vigilantai
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: vigilantai
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: loki
