apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vigilantai

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - secret.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - ../../monitoring/grafana/dashboards/platform-overview.json
      - ../../monitoring/grafana/dashboards/backend.json
      - ../../monitoring/grafana/dashboards/camera-gateway.json
      - ../../monitoring/grafana/dashboards/ai-service.json
      - ../../monitoring/grafana/dashboards/dashboard-monitoring.json
    options:
      disableNameSuffixHash: true
