apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: vigilantai
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: vigilantai
type: Opaque
stringData:
  admin-user: admin
  admin-password: changeme
